// Package pb implements the ITK instruction protocol types with hand-written
// proto3 binary marshaling. This file can be regenerated by run_itk.sh using
// protoc, but the hand-written implementation is self-contained and does not
// require protoc to compile.
//
// The types correspond to instruction.proto in the a2a-itk repository.
package pb

import (
	"fmt"

	"google.golang.org/protobuf/encoding/protowire"
)

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

// Instruction is the top-level ITK traversal instruction.
type Instruction struct {
	CallAgent      *CallAgent
	ReturnResponse *ReturnResponse
	Steps          *SeriesOfSteps
}

func (m *Instruction) GetCallAgent() *CallAgent {
	if m != nil {
		return m.CallAgent
	}
	return nil
}

func (m *Instruction) GetReturnResponse() *ReturnResponse {
	if m != nil {
		return m.ReturnResponse
	}
	return nil
}

func (m *Instruction) GetSteps() *SeriesOfSteps {
	if m != nil {
		return m.Steps
	}
	return nil
}

// CallAgent instructs the agent to call a remote agent.
type CallAgent struct {
	Transport      string
	AgentCardUri   string
	Instruction    *Instruction
	Streaming      bool
	SendMessage    *SendMessageBehavior
	PushNotification *PushNotificationBehavior
	Resubscribe    *ResubscribeBehavior
}

func (m *CallAgent) GetTransport() string     { if m != nil { return m.Transport }; return "" }
func (m *CallAgent) GetAgentCardUri() string { if m != nil { return m.AgentCardUri }; return "" }
func (m *CallAgent) GetInstruction() *Instruction { if m != nil { return m.Instruction }; return nil }
func (m *CallAgent) GetStreaming() bool      { if m != nil { return m.Streaming }; return false }
func (m *CallAgent) GetSendMessage() *SendMessageBehavior { if m != nil { return m.SendMessage }; return nil }
func (m *CallAgent) GetPushNotification() *PushNotificationBehavior { if m != nil { return m.PushNotification }; return nil }
func (m *CallAgent) GetResubscribe() *ResubscribeBehavior { if m != nil { return m.Resubscribe }; return nil }

// ReturnResponse instructs the agent to return a fixed response.
type ReturnResponse struct {
	Response string
	HoldTask bool
}

func (m *ReturnResponse) GetResponse() string { if m != nil { return m.Response }; return "" }
func (m *ReturnResponse) GetHoldTask() bool   { if m != nil { return m.HoldTask }; return false }

// ResponseGenerator is the enum for SeriesOfSteps.
type ResponseGenerator int32

const (
	ResponseGeneratorUnspecified ResponseGenerator = 0
	ResponseGeneratorConcat      ResponseGenerator = 1
)

// SeriesOfSteps executes a series of instructions and concatenates results.
type SeriesOfSteps struct {
	Instructions      []*Instruction
	ResponseGenerator ResponseGenerator
}

func (m *SeriesOfSteps) GetInstructions() []*Instruction { if m != nil { return m.Instructions }; return nil }
func (m *SeriesOfSteps) GetResponseGenerator() ResponseGenerator { if m != nil { return m.ResponseGenerator }; return ResponseGeneratorUnspecified }

// SendMessageBehavior is an empty message indicating send_message behavior.
type SendMessageBehavior struct{}

// PushNotificationBehavior carries the push notification URL.
type PushNotificationBehavior struct {
	Url string
}

func (m *PushNotificationBehavior) GetUrl() string { if m != nil { return m.Url }; return "" }

// ResubscribeBehavior is an empty message indicating resubscribe behavior.
type ResubscribeBehavior struct{}

// ---------------------------------------------------------------------------
// Marshal / Unmarshal
// ---------------------------------------------------------------------------

// Marshal serializes an Instruction to proto3 binary format.
func Marshal(m *Instruction) ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	var b []byte
	if m.CallAgent != nil {
		nested, err := marshalCallAgent(m.CallAgent)
		if err != nil {
			return nil, err
		}
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendBytes(b, nested)
	}
	if m.ReturnResponse != nil {
		nested, err := marshalReturnResponse(m.ReturnResponse)
		if err != nil {
			return nil, err
		}
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendBytes(b, nested)
	}
	if m.Steps != nil {
		nested, err := marshalSeriesOfSteps(m.Steps)
		if err != nil {
			return nil, err
		}
		b = protowire.AppendTag(b, 3, protowire.BytesType)
		b = protowire.AppendBytes(b, nested)
	}
	return b, nil
}

// Unmarshal deserializes an Instruction from proto3 binary format.
func Unmarshal(data []byte, m *Instruction) error {
	if m == nil {
		return fmt.Errorf("pb: Unmarshal: nil Instruction")
	}
	for len(data) > 0 {
		num, typ, n := protowire.ConsumeTag(data)
		if n < 0 {
			return fmt.Errorf("pb: failed to consume tag: %v", protowire.ParseError(n))
		}
		data = data[n:]
		switch num {
		case 1: // call_agent
			if typ != protowire.BytesType {
				return fmt.Errorf("pb: call_agent: expected bytes type, got %v", typ)
			}
			v, nn := protowire.ConsumeBytes(data)
			if nn < 0 {
				return fmt.Errorf("pb: failed to consume call_agent bytes: %v", protowire.ParseError(nn))
			}
			data = data[nn:]
			m.CallAgent = &CallAgent{}
			if err := unmarshalCallAgent(v, m.CallAgent); err != nil {
				return err
			}
			m.ReturnResponse = nil
			m.Steps = nil
		case 2: // return_response
			if typ != protowire.BytesType {
				return fmt.Errorf("pb: return_response: expected bytes type, got %v", typ)
			}
			v, nn := protowire.ConsumeBytes(data)
			if nn < 0 {
				return fmt.Errorf("pb: failed to consume return_response bytes: %v", protowire.ParseError(nn))
			}
			data = data[nn:]
			m.ReturnResponse = &ReturnResponse{}
			if err := unmarshalReturnResponse(v, m.ReturnResponse); err != nil {
				return err
			}
			m.CallAgent = nil
			m.Steps = nil
		case 3: // steps
			if typ != protowire.BytesType {
				return fmt.Errorf("pb: steps: expected bytes type, got %v", typ)
			}
			v, nn := protowire.ConsumeBytes(data)
			if nn < 0 {
				return fmt.Errorf("pb: failed to consume steps bytes: %v", protowire.ParseError(nn))
			}
			data = data[nn:]
			m.Steps = &SeriesOfSteps{}
			if err := unmarshalSeriesOfSteps(v, m.Steps); err != nil {
				return err
			}
			m.CallAgent = nil
			m.ReturnResponse = nil
		default:
			// Skip unknown fields.
			nn := protowire.ConsumeFieldValue(num, typ, data)
			if nn < 0 {
				return fmt.Errorf("pb: failed to skip unknown field %d: %v", num, protowire.ParseError(nn))
			}
			data = data[nn:]
		}
	}
	return nil
}

func marshalCallAgent(m *CallAgent) ([]byte, error) {
	var b []byte
	if m.Transport != "" {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, m.Transport)
	}
	if m.AgentCardUri != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, m.AgentCardUri)
	}
	if m.Instruction != nil {
		nested, err := Marshal(m.Instruction)
		if err != nil {
			return nil, err
		}
		b = protowire.AppendTag(b, 3, protowire.BytesType)
		b = protowire.AppendBytes(b, nested)
	}
	if m.Streaming {
		b = protowire.AppendTag(b, 4, protowire.VarintType)
		b = protowire.AppendVarint(b, 1)
	}
	if m.SendMessage != nil {
		b = protowire.AppendTag(b, 5, protowire.BytesType)
		b = protowire.AppendBytes(b, nil) // empty message
	}
	if m.PushNotification != nil {
		nested, err := marshalPushNotification(m.PushNotification)
		if err != nil {
			return nil, err
		}
		b = protowire.AppendTag(b, 6, protowire.BytesType)
		b = protowire.AppendBytes(b, nested)
	}
	if m.Resubscribe != nil {
		b = protowire.AppendTag(b, 7, protowire.BytesType)
		b = protowire.AppendBytes(b, nil) // empty message
	}
	return b, nil
}

func unmarshalCallAgent(data []byte, m *CallAgent) error {
	for len(data) > 0 {
		num, typ, n := protowire.ConsumeTag(data)
		if n < 0 {
			return fmt.Errorf("pb: CallAgent: failed to consume tag: %v", protowire.ParseError(n))
		}
		data = data[n:]
		switch num {
		case 1: // transport
			v, nn := protowire.ConsumeString(data)
			if nn < 0 {
				return fmt.Errorf("pb: CallAgent: failed to consume transport: %v", protowire.ParseError(nn))
			}
			data = data[nn:]
			m.Transport = v
		case 2: // agent_card_uri
			v, nn := protowire.ConsumeString(data)
			if nn < 0 {
				return fmt.Errorf("pb: CallAgent: failed to consume agent_card_uri: %v", protowire.ParseError(nn))
			}
			data = data[nn:]
			m.AgentCardUri = v
		case 3: // instruction
			v, nn := protowire.ConsumeBytes(data)
			if nn < 0 {
				return fmt.Errorf("pb: CallAgent: failed to consume instruction: %v", protowire.ParseError(nn))
			}
			data = data[nn:]
			m.Instruction = &Instruction{}
			if err := Unmarshal(v, m.Instruction); err != nil {
				return err
			}
		case 4: // streaming
			v, nn := protowire.ConsumeVarint(data)
			if nn < 0 {
				return fmt.Errorf("pb: CallAgent: failed to consume streaming: %v", protowire.ParseError(nn))
			}
			data = data[nn:]
			m.Streaming = v != 0
		case 5: // send_message
			v, nn := protowire.ConsumeBytes(data)
			if nn < 0 {
				return fmt.Errorf("pb: CallAgent: failed to consume send_message: %v", protowire.ParseError(nn))
			}
			data = data[nn:]
			m.SendMessage = &SendMessageBehavior{}
			m.PushNotification = nil
			m.Resubscribe = nil
			_ = v // empty message, ignore content
		case 6: // push_notification
			v, nn := protowire.ConsumeBytes(data)
			if nn < 0 {
				return fmt.Errorf("pb: CallAgent: failed to consume push_notification: %v", protowire.ParseError(nn))
			}
			data = data[nn:]
			m.PushNotification = &PushNotificationBehavior{}
			if err := unmarshalPushNotification(v, m.PushNotification); err != nil {
				return err
			}
			m.SendMessage = nil
			m.Resubscribe = nil
		case 7: // resubscribe
			v, nn := protowire.ConsumeBytes(data)
			if nn < 0 {
				return fmt.Errorf("pb: CallAgent: failed to consume resubscribe: %v", protowire.ParseError(nn))
			}
			data = data[nn:]
			m.Resubscribe = &ResubscribeBehavior{}
			m.SendMessage = nil
			m.PushNotification = nil
			_ = v
		default:
			nn := protowire.ConsumeFieldValue(num, typ, data)
			if nn < 0 {
				return fmt.Errorf("pb: CallAgent: failed to skip unknown field %d: %v", num, protowire.ParseError(nn))
			}
			data = data[nn:]
		}
	}
	return nil
}

func marshalReturnResponse(m *ReturnResponse) ([]byte, error) {
	var b []byte
	if m.Response != "" {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, m.Response)
	}
	if m.HoldTask {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, 1)
	}
	return b, nil
}

func unmarshalReturnResponse(data []byte, m *ReturnResponse) error {
	for len(data) > 0 {
		num, typ, n := protowire.ConsumeTag(data)
		if n < 0 {
			return fmt.Errorf("pb: ReturnResponse: failed to consume tag: %v", protowire.ParseError(n))
		}
		data = data[n:]
		switch num {
		case 1: // response
			v, nn := protowire.ConsumeString(data)
			if nn < 0 {
				return fmt.Errorf("pb: ReturnResponse: failed to consume response: %v", protowire.ParseError(nn))
			}
			data = data[nn:]
			m.Response = v
		case 2: // hold_task
			v, nn := protowire.ConsumeVarint(data)
			if nn < 0 {
				return fmt.Errorf("pb: ReturnResponse: failed to consume hold_task: %v", protowire.ParseError(nn))
			}
			data = data[nn:]
			m.HoldTask = v != 0
		default:
			nn := protowire.ConsumeFieldValue(num, typ, data)
			if nn < 0 {
				return fmt.Errorf("pb: ReturnResponse: failed to skip unknown field %d: %v", num, protowire.ParseError(nn))
			}
			data = data[nn:]
		}
	}
	return nil
}

func marshalSeriesOfSteps(m *SeriesOfSteps) ([]byte, error) {
	var b []byte
	for _, inst := range m.Instructions {
		nested, err := Marshal(inst)
		if err != nil {
			return nil, err
		}
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendBytes(b, nested)
	}
	if m.ResponseGenerator != ResponseGeneratorUnspecified {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.ResponseGenerator))
	}
	return b, nil
}

func unmarshalSeriesOfSteps(data []byte, m *SeriesOfSteps) error {
	for len(data) > 0 {
		num, typ, n := protowire.ConsumeTag(data)
		if n < 0 {
			return fmt.Errorf("pb: SeriesOfSteps: failed to consume tag: %v", protowire.ParseError(n))
		}
		data = data[n:]
		switch num {
		case 1: // instructions (repeated)
			v, nn := protowire.ConsumeBytes(data)
			if nn < 0 {
				return fmt.Errorf("pb: SeriesOfSteps: failed to consume instructions: %v", protowire.ParseError(nn))
			}
			data = data[nn:]
			inst := &Instruction{}
			if err := Unmarshal(v, inst); err != nil {
				return err
			}
			m.Instructions = append(m.Instructions, inst)
		case 2: // response_generator
			v, nn := protowire.ConsumeVarint(data)
			if nn < 0 {
				return fmt.Errorf("pb: SeriesOfSteps: failed to consume response_generator: %v", protowire.ParseError(nn))
			}
			data = data[nn:]
			m.ResponseGenerator = ResponseGenerator(v)
		default:
			nn := protowire.ConsumeFieldValue(num, typ, data)
			if nn < 0 {
				return fmt.Errorf("pb: SeriesOfSteps: failed to skip unknown field %d: %v", num, protowire.ParseError(nn))
			}
			data = data[nn:]
		}
	}
	return nil
}

func marshalPushNotification(m *PushNotificationBehavior) ([]byte, error) {
	var b []byte
	if m.Url != "" {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, m.Url)
	}
	return b, nil
}

func unmarshalPushNotification(data []byte, m *PushNotificationBehavior) error {
	for len(data) > 0 {
		num, typ, n := protowire.ConsumeTag(data)
		if n < 0 {
			return fmt.Errorf("pb: PushNotificationBehavior: failed to consume tag: %v", protowire.ParseError(n))
		}
		data = data[n:]
		switch num {
		case 1: // url
			v, nn := protowire.ConsumeString(data)
			if nn < 0 {
				return fmt.Errorf("pb: PushNotificationBehavior: failed to consume url: %v", protowire.ParseError(nn))
			}
			data = data[nn:]
			m.Url = v
		default:
			nn := protowire.ConsumeFieldValue(num, typ, data)
			if nn < 0 {
				return fmt.Errorf("pb: PushNotificationBehavior: failed to skip unknown field %d: %v", num, protowire.ParseError(nn))
			}
			data = data[nn:]
		}
	}
	return nil
}
