name: ITK

on:
  push:
    branches: [main]
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/CODEOWNERS'

permissions:
  contents: read

jobs:
  itk:
    name: ITK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache-dependency-path: |
            go.sum
            example/itk/go.mod

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run ITK Tests
        run: bash run_itk.sh
        working-directory: example/itk
        env:
          A2A_ITK_REVISION: main
